In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [2]:
model = Sequential()
embedding_layer = Embedding(input_dim=10, output_dim=4, input_length=2)
model.add(embedding_layer)
model.compile('adam','mse')

In [8]:
input_data = np.array([[3,4],
                       [0,9],
                       [2,1]])
pred = model.predict(input_data)
print(input_data.shape)
print(pred)

(3, 2)
[[[ 0.04844624 -0.00485881 -0.0492545  -0.01502136]
  [-0.00177217 -0.0407959   0.04064612  0.04900885]]

 [[ 0.00861184  0.0215025  -0.02791776  0.04272671]
  [ 0.0317778   0.02580867 -0.04938618 -0.01140486]]

 [[ 0.04995607  0.04816678 -0.02378471 -0.04055023]
  [ 0.04557535  0.01964304 -0.04443607 -0.02900742]]]


In [11]:
embedding_layer.weights

[<tf.Variable 'embedding/embeddings:0' shape=(10, 4) dtype=float32, numpy=
 array([[ 0.00861184,  0.0215025 , -0.02791776,  0.04272671],
        [ 0.04557535,  0.01964304, -0.04443607, -0.02900742],
        [ 0.04995607,  0.04816678, -0.02378471, -0.04055023],
        [ 0.04844624, -0.00485881, -0.0492545 , -0.01502136],
        [-0.00177217, -0.0407959 ,  0.04064612,  0.04900885],
        [ 0.02726105, -0.03905716, -0.04823518,  0.03205652],
        [-0.04778229,  0.01817701, -0.01282474,  0.00999111],
        [-0.01989874,  0.00062699, -0.03477405, -0.00864558],
        [-0.01922343,  0.02229274,  0.04035015, -0.00317257],
        [ 0.0317778 ,  0.02580867, -0.04938618, -0.01140486]],
       dtype=float32)>]

In [12]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Embedding,Dense

In [13]:
# Define 10 restaurant reviews
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
#Define labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [27]:
vocab_size=1000
max_input_length = 20

In [17]:
tokenizer = Tokenizer(num_words=vocab_size)

In [20]:
tokenizer.fit_on_texts(reviews)

In [23]:
tokenized_sequences = tokenizer.texts_to_sequences(reviews)

In [28]:
padded_tokens = pad_sequences(tokenized_sequences, maxlen = max_input_length, padding='post', truncating='post')
print(padded_tokens)

[[ 4  5  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [10  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [13 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [15 16 17 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [33]:
padded_tokens.shape

(10, 20)

In [31]:
test_embedding_layer = Embedding(vocab_size, 4, input_length=max_input_length)

In [34]:
test_embedding_layer(padded_tokens).shape

TensorShape([10, 20, 4])

In [38]:
Flatten()(test_embedding_layer(padded_tokens)).shape

TensorShape([10, 80])

In [35]:
Vocab_size = 50
encoded_reviews = [one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

encoded reviews: [[39, 23, 9], [45, 42], [3, 22], [34, 34], [45, 34], [25], [25, 23], [3], [35, 45], [33, 16, 45, 15]]


In [36]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[39 23  9  0]
 [45 42  0  0]
 [ 3 22  0  0]
 [34 34  0  0]
 [45 34  0  0]
 [25  0  0  0]
 [25 23  0  0]
 [ 3  0  0  0]
 [35 45  0  0]
 [33 16 45 15]]


In [39]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [40]:
model.fit(padded_reviews,labels,epochs=100,verbose=0)

In [46]:
embedding_layer.weights

[<tf.Variable 'embedding_3/embeddings:0' shape=(50, 8) dtype=float32, numpy=
 array([[-0.11303274,  0.1393673 , -0.1182963 ,  0.10176156,  0.12531956,
         -0.07254126, -0.12246963,  0.05851728],
        [-0.0049333 , -0.03537079, -0.02483976, -0.00382701,  0.01019424,
         -0.01850227,  0.01779348,  0.03818789],
        [-0.01681844,  0.03955699, -0.04310925, -0.04206495,  0.01937217,
          0.01382533,  0.01335385, -0.0225739 ],
        [ 0.07480194, -0.00491694,  0.05680364,  0.05407056, -0.04219474,
         -0.08120994, -0.01496705,  0.08853046],
        [-0.00569038, -0.01568059, -0.04147396,  0.01380218, -0.02635579,
         -0.03828931,  0.04772403,  0.01264602],
        [ 0.03216541,  0.01028331, -0.02223557,  0.0347763 , -0.03460439,
         -0.02847245,  0.01573749,  0.00169037],
        [ 0.00771175, -0.03809086, -0.02883612,  0.04323464, -0.03003935,
         -0.02489585, -0.02675251,  0.04714814],
        [ 0.03407318, -0.04705732, -0.0289905 , -0.00146979, -